# Generated by Django 5.2 on 2025-06-22 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meroshare', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meroshareaccount',
            old_name='_dp',
            new_name='dp',
        ),
    ]
