# Generated by Django 5.2 on 2025-06-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meroshare', '0002_rename__dp_meroshareaccount_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meroshareaccount',
            name='alias_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
