# Generated by Django 5.2 on 2025-06-26 08:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmsaccount',
            name='_username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tmsaccount',
            name='broker_number',
            field=models.CharField(max_length=5),
        ),
        migrations.AddConstraint(
            model_name='tmsaccount',
            constraint=models.UniqueConstraint(fields=('broker_number', '_username'), name='unique_broker_username'),
        ),
    ]
