# Generated by Django 5.2 on 2025-06-26 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0002_alter_tmsaccount__username_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tmsaccount',
            name='unique_broker_username',
        ),
        migrations.AddField(
            model_name='tmsaccount',
            name='username_hash',
            field=models.CharField(default='dffs', editable=False, max_length=64),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='tmsaccount',
            constraint=models.UniqueConstraint(fields=('broker_number', 'username_hash'), name='unique_broker_username'),
        ),
    ]
